// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oqdqglckmvnfvqfdcmna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xZHFnbGNrbXZuZnZxZmRjbW5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3OTA4OTYsImV4cCI6MjA1NzM2Njg5Nn0.ZKl7TYBcV_Ky8d-vyCRqWQ56hE-eLZkrAC4qSE6gePk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);